---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: gol-deployment
    labels:
      name: gol
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: gol
    template:
      metadata:
        labels:
          app: gol
      spec:
        imagePullSecrets:
          - name: reposecret
        containers:
        - name: gol
          image: 10.160.0.4:8084/golproject:1.0
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          resources:
            requests:
              cpu: "500m"
              memory: "128Mi"
            limits: 
              cpu: "1000m"
              memory: "512Mi"
          ports:
          - name: gol
            containerPort: 8080



---
# Node Port Service
  apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: gol
    name: gol
  spec:
    type: NodePort
    ports:
      - port: 8080
        targetPort: 8080
        protocol: TCP 
        nodeport: 32005
    selector:
      name: gol